name: Flutter Test
on:
  push:
    paths:
      - 'carpool_app/**'
      - '.github/workflows/flutter_test.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'carpool_app/**'
      - '.github/workflows/flutter_test.yml'
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.9'
        
      - name: Get all Flutter Packages
        working-directory: carpool_app
        run: flutter pub get

      - name: Run Flutter Test
        working-directory: carpool_app
        run: flutter test --coverage
